defmodule Tracker.Notifications.Notification do
  @moduledoc """
  A durable, per-user notification generated by the fan-out workers.

  Notifications are references plus a `type`; the full detail is rendered on
  read from the linked source records. Each row carries a unique `dedup_key`
  so worker retries and reconciliation reruns are no-ops.
  """

  use Ash.Resource,
    otp_app: :tracker,
    domain: Tracker.Notifications,
    authorizers: [Ash.Policy.Authorizer],
    data_layer: AshPostgres.DataLayer,
    notifiers: [Ash.Notifier.PubSub]

  @types [
    :package_version_changed,
    :package_added,
    :package_removed,
    :channel_revision_published,
    :change_propagated
  ]

  postgres do
    table "notifications"
    repo Tracker.Repo

    references do
      reference :user, on_delete: :delete
      reference :package, on_delete: :delete
      reference :channel, on_delete: :delete
      reference :channel_revision, on_delete: :delete
      reference :change, on_delete: :delete
      reference :change_branch, on_delete: :delete
    end
  end

  code_interface do
    define :for_user
    define :mark_read
    define :mark_unread
    define :destroy
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      description "System-only: record a notification, idempotent on dedup_key."

      accept [
        :user_id,
        :type,
        :package_id,
        :channel_id,
        :channel_revision_id,
        :change_id,
        :change_branch_id,
        :occurred_at,
        :dedup_key
      ]

      upsert? true
      upsert_identity :unique_dedup_key
      upsert_fields []
    end

    read :for_user do
      description "List the actor's notifications, newest first; optionally scoped to a revision."

      argument :channel_revision_id, :integer

      prepare build(
                sort: [occurred_at: :desc],
                load: [
                  :package,
                  :channel,
                  :change,
                  channel_revision: [:channel],
                  change_branch: [:change]
                ]
              )

      filter expr(
               if not is_nil(^arg(:channel_revision_id)) do
                 channel_revision_id == ^arg(:channel_revision_id)
               else
                 true
               end
             )
    end

    update :mark_read do
      description "Mark a notification read."
      accept []
      require_atomic? false
      change set_attribute(:read_at, &DateTime.utc_now/0)
    end

    update :mark_unread do
      description "Mark a notification unread."
      accept []
      change set_attribute(:read_at, nil)
    end
  end

  policies do
    policy action_type([:read, :update, :destroy]) do
      authorize_if expr(user_id == ^actor(:id))
    end
  end

  pub_sub do
    module Phoenix.PubSub
    name Tracker.PubSub
    prefix "notifications"

    publish :create, [[:user_id, "any"]]
  end

  attributes do
    integer_primary_key :id

    attribute :type, :atom do
      allow_nil? false
      public? true
      constraints one_of: @types
    end

    attribute :occurred_at, :utc_datetime, allow_nil?: false, public?: true
    attribute :read_at, :utc_datetime, public?: true
    attribute :dedup_key, :string, allow_nil?: false, public?: true

    timestamps()
  end

  relationships do
    belongs_to :user, Tracker.Accounts.User, attribute_type: :uuid, allow_nil?: false
    belongs_to :package, Tracker.Nixpkgs.Package, attribute_type: :integer
    belongs_to :channel, Tracker.Nixpkgs.Channel, attribute_type: :integer
    belongs_to :channel_revision, Tracker.Nixpkgs.ChannelRevision, attribute_type: :integer
    belongs_to :change, Tracker.Nixpkgs.Change, attribute_type: :integer
    belongs_to :change_branch, Tracker.Nixpkgs.ChangeBranch, attribute_type: :integer
  end

  identities do
    identity :unique_dedup_key, [:dedup_key]
  end

  @doc """
  Idempotently records a batch of notification maps, broadcasting an insert
  for each newly created row. Conflicts on `dedup_key` are no-ops, so worker
  retries never duplicate or re-broadcast.
  """
  @spec fanout([map()]) :: :ok
  def fanout([]), do: :ok

  def fanout(rows) when is_list(rows) do
    Ash.bulk_create!(rows, __MODULE__, :create,
      return_records?: false,
      notify?: true,
      authorize?: false
    )

    :ok
  end
end
