defmodule Tracker.Repo.Migrations.AddRepoPullRequest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pull_requests, primary_key: false) do
      add :pr_id, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:pull_requests)
  end
end