defmodule Tracker.Repo.Migrations.AddPackageRevision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:package_revisions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :version, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :package_id,
          references(:packages,
            column: :id,
            name: "package_revisions_package_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :channel_revision_id, :bigint, null: false
    end

    create table(:channel_revisions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:package_revisions) do
      modify :channel_revision_id,
             references(:channel_revisions,
               column: :id,
               name: "package_revisions_channel_revision_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create unique_index(:package_revisions, [:channel_revision_id, :package_id],
             name: "package_revisions_unique_package_revision_index"
           )

    alter table(:channel_revisions) do
      add :channel, :text, null: false
      add :revision, :text, null: false
      add :result, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:channel_revisions, [:channel, :revision],
             name: "channel_revisions_unique_channel_revision_index"
           )
  end

  def down do
    drop_if_exists unique_index(:channel_revisions, [:channel, :revision],
                     name: "channel_revisions_unique_channel_revision_index"
                   )

    alter table(:channel_revisions) do
      remove :updated_at
      remove :inserted_at
      remove :result
      remove :revision
      remove :channel
    end

    drop_if_exists unique_index(:package_revisions, [:channel_revision_id, :package_id],
                     name: "package_revisions_unique_package_revision_index"
                   )

    drop constraint(:package_revisions, "package_revisions_channel_revision_id_fkey")

    alter table(:package_revisions) do
      modify :channel_revision_id, :bigint
    end

    drop table(:channel_revisions)

    drop constraint(:package_revisions, "package_revisions_package_id_fkey")

    drop table(:package_revisions)
  end
end
