defmodule Tracker.Repo.Migrations.GithubId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :email
      remove :oidc_id
      add :github_id, :bigint, null: false
    end

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:github_id], name: "users_unique_id_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_id_index")

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :github_id
      add :oidc_id, :text, null: false
      add :email, :text
    end
  end
end
