defmodule Tracker.Repo.Migrations.UserInfo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
      add :oidc_id, :text, null: false
      add :email, :text
      add :github_username, :text, null: false
    end
  end

  def down do
    alter table(:users) do
      remove :github_username
      remove :email
      remove :oidc_id
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end
end
