defmodule Tracker.Repo.Migrations.GithubUniqueUsername do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_id_index")

    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create unique_index(:users, [:github_username], name: "users_unique_github_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:github_username],
                     name: "users_unique_github_username_index"
                   )

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create unique_index(:users, [:github_id], name: "users_unique_id_index")
  end
end
