defmodule Tracker.Repo.Migrations.AllowBrowserTimeZone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :time_zone, :text, null: true, default: nil
    end

    execute "UPDATE users SET time_zone = NULL WHERE time_zone = 'Etc/UTC'"
  end

  def down do
    execute "UPDATE users SET time_zone = 'Etc/UTC' WHERE time_zone IS NULL"

    alter table(:users) do
      modify :time_zone, :text, null: false, default: "Etc/UTC"
    end
  end
end
