defmodule Tracker.Repo.Migrations.AddIngestionPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingestion_runs, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :type, :text, null: false
      add :status, :text, null: false
      add :started_at, :utc_datetime, null: false
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:ingestion_pipelines, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :channel, :text, null: false
      add :revision, :text, null: false
      add :base_url, :text, null: false
      add :released_at, :utc_datetime, null: false
      add :channel_revision_id, :bigint
      add :status, :text, null: false
      add :active_steps, {:array, :text}, null: false
      add :completed_steps, {:array, :text}, null: false, default: []
      add :failed_step, :text
      add :error, :text
      add :sequence, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ingestion_run_id,
          references(:ingestion_runs,
            column: :id,
            name: "ingestion_pipelines_ingestion_run_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:ingestion_pipelines, [:channel, :revision],
             name: "ingestion_pipelines_unique_pipeline_channel_revision_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ingestion_pipelines, [:channel, :revision],
                     name: "ingestion_pipelines_unique_pipeline_channel_revision_index"
                   )

    drop constraint(:ingestion_pipelines, "ingestion_pipelines_ingestion_run_id_fkey")

    drop table(:ingestion_pipelines)

    drop table(:ingestion_runs)
  end
end
