defmodule Tracker.Repo.Migrations.AddPackageSubscriptionEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:package_subscriptions) do
      add :events, {:array, :text},
        null: false,
        default: ["package_version_changed", "package_added", "package_removed"]
    end
  end

  def down do
    alter table(:package_subscriptions) do
      remove :events
    end
  end
end
