defmodule Tracker.Repo.Migrations.AddPredecessorToPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ingestion_pipelines) do
      add :predecessor_id,
          references(:ingestion_pipelines,
            column: :id,
            name: "ingestion_pipelines_predecessor_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:ingestion_pipelines, "ingestion_pipelines_predecessor_id_fkey")

    alter table(:ingestion_pipelines) do
      remove :predecessor_id
    end
  end
end
