defmodule Tracker.Repo.Migrations.AddHydraStatusToChannels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channels) do
      add :hydra_build_failed?, :boolean
      add :hydra_project, :text
      add :hydra_jobset, :text
      add :hydra_exported_job, :text
      add :hydra_checked_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:channels) do
      remove :hydra_checked_at
      remove :hydra_exported_job
      remove :hydra_jobset
      remove :hydra_project
      remove :hydra_build_failed?
    end
  end
end
