defmodule Tracker.Repo.Migrations.SpansTargetSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:option_events)

    drop table(:option_revision_files)

    drop table(:package_events)

    drop table(:package_revisions)

    drop table(:option_revisions)

    alter table(:packages) do
      remove :set_version
      remove :package_set
      remove :licenses
      remove :position
      remove :homepage
      remove :description
    end

    create table(:package_spans, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :valid, :tstzrange, null: false
      add :version, :text
      add :description, :text
      add :homepage, {:array, :text}
      add :licenses, {:array, :text}
      add :position, :text
      add :package_set, :text
      add :set_version, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:channels,
            column: :id,
            name: "package_spans_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :package_id,
          references(:packages,
            column: :id,
            name: "package_spans_package_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create table(:option_spans, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :valid, :tstzrange, null: false
      add :description, :text
      add :type, :text
      add :default, :text
      add :example, :text
      add :read_only, :boolean, default: false
      add :loc, {:array, :text}
      add :related_packages, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:channels,
            column: :id,
            name: "option_spans_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :option_id,
          references(:options,
            column: :id,
            name: "option_spans_option_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create table(:option_file_spans, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :valid, :tstzrange, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:channels,
            column: :id,
            name: "option_file_spans_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :option_id,
          references(:options,
            column: :id,
            name: "option_file_spans_option_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_id,
          references(:files,
            column: :id,
            name: "option_file_spans_file_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    execute("""
    ALTER TABLE option_file_spans ADD CONSTRAINT option_file_spans_no_overlap EXCLUDE USING gist (channel_id WITH =, option_id WITH =, file_id WITH =, valid WITH &&)
    """)

    execute("""
    CREATE INDEX option_file_spans_current ON option_file_spans (channel_id, option_id, file_id) WHERE upper_inf(valid)
    """)

    execute("""
    ALTER TABLE option_spans ADD CONSTRAINT option_spans_no_overlap EXCLUDE USING gist (channel_id WITH =, option_id WITH =, valid WITH &&)
    """)

    execute("""
    CREATE INDEX option_spans_current ON option_spans (channel_id, option_id) WHERE upper_inf(valid)
    """)

    execute("""
    ALTER TABLE package_spans ADD CONSTRAINT package_spans_no_overlap EXCLUDE USING gist (channel_id WITH =, package_id WITH =, valid WITH &&)
    """)

    execute("""
    CREATE INDEX package_spans_current ON package_spans (channel_id, package_id) WHERE upper_inf(valid)
    """)
  end

  def down do
    execute("""
    DROP INDEX package_spans_current
    """)

    execute("""
    ALTER TABLE package_spans DROP CONSTRAINT package_spans_no_overlap
    """)

    execute("""
    DROP INDEX option_spans_current
    """)

    execute("""
    ALTER TABLE option_spans DROP CONSTRAINT option_spans_no_overlap
    """)

    execute("""
    DROP INDEX option_file_spans_current
    """)

    execute("""
    ALTER TABLE option_file_spans DROP CONSTRAINT option_file_spans_no_overlap
    """)

    drop constraint(:option_file_spans, "option_file_spans_channel_id_fkey")

    drop constraint(:option_file_spans, "option_file_spans_option_id_fkey")

    drop constraint(:option_file_spans, "option_file_spans_file_id_fkey")

    drop table(:option_file_spans)

    drop constraint(:option_spans, "option_spans_channel_id_fkey")

    drop constraint(:option_spans, "option_spans_option_id_fkey")

    drop table(:option_spans)

    drop constraint(:package_spans, "package_spans_channel_id_fkey")

    drop constraint(:package_spans, "package_spans_package_id_fkey")

    drop table(:package_spans)

    alter table(:packages) do
      add :description, :text
      add :homepage, {:array, :text}
      add :position, :text
      add :licenses, {:array, :text}
      add :package_set, :text
      add :set_version, :text
    end

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
