defmodule Tracker.Repo.Migrations.AddChannelIdToPipelines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ingestion_pipelines) do
      remove :channel

      add :channel_id,
          references(:channels,
            column: :id,
            name: "ingestion_pipelines_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:ingestion_pipelines, [:channel, :revision],
                     name: "ingestion_pipelines_unique_pipeline_channel_revision_index"
                   )

    create unique_index(:ingestion_pipelines, [:channel_id, :revision],
             name: "ingestion_pipelines_unique_pipeline_channel_revision_index"
           )
  end

  def down do
    drop_if_exists unique_index(:ingestion_pipelines, [:channel_id, :revision],
                     name: "ingestion_pipelines_unique_pipeline_channel_revision_index"
                   )

    create unique_index(:ingestion_pipelines, [:channel, :revision],
             name: "ingestion_pipelines_unique_pipeline_channel_revision_index"
           )

    drop constraint(:ingestion_pipelines, "ingestion_pipelines_channel_id_fkey")

    alter table(:ingestion_pipelines) do
      remove :channel_id
      add :channel, :text, null: false
    end
  end
end
