defmodule Tracker.Repo.Migrations.AddChannelIdToChangeChannels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:change_channels) do
      remove :channel

      add :channel_id,
          references(:channels,
            column: :id,
            name: "change_channels_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:change_channels, [:change_id, :channel],
                     name: "change_channels_unique_change_channel_index"
                   )

    create unique_index(:change_channels, [:change_id, :channel_id],
             name: "change_channels_unique_change_channel_index"
           )
  end

  def down do
    drop_if_exists unique_index(:change_channels, [:change_id, :channel_id],
                     name: "change_channels_unique_change_channel_index"
                   )

    create unique_index(:change_channels, [:change_id, :channel],
             name: "change_channels_unique_change_channel_index"
           )

    drop constraint(:change_channels, "change_channels_channel_id_fkey")

    alter table(:change_channels) do
      remove :channel_id
      add :channel, :text, null: false
    end
  end
end
