defmodule Tracker.Repo.Migrations.AddChannelIdToChannelRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channel_revisions) do
      remove :channel

      add :channel_id,
          references(:channels,
            column: :id,
            name: "channel_revisions_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:channel_revisions, [:channel, :revision],
                     name: "channel_revisions_unique_channel_revision_index"
                   )

    create unique_index(:channel_revisions, [:channel_id, :revision],
             name: "channel_revisions_unique_channel_revision_index"
           )
  end

  def down do
    drop_if_exists unique_index(:channel_revisions, [:channel_id, :revision],
                     name: "channel_revisions_unique_channel_revision_index"
                   )

    create unique_index(:channel_revisions, [:channel, :revision],
             name: "channel_revisions_unique_channel_revision_index"
           )

    drop constraint(:channel_revisions, "channel_revisions_channel_id_fkey")

    alter table(:channel_revisions) do
      remove :channel_id
      add :channel, :text, null: false
    end
  end
end
