defmodule Tracker.Repo.Migrations.AddSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:package_subscriptions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "package_subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :package_id,
          references(:packages,
            column: :id,
            name: "package_subscriptions_package_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :channel_id,
          references(:channels,
            column: :id,
            name: "package_subscriptions_channel_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:package_subscriptions, [:user_id, :package_id, :channel_id],
             name: "package_subscriptions_unique_package_subscription_index",
             nulls_distinct: false
           )

    create table(:channel_subscriptions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "channel_subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :channel_id,
          references(:channels,
            column: :id,
            name: "channel_subscriptions_channel_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:channel_subscriptions, [:user_id, :channel_id],
             name: "channel_subscriptions_unique_channel_subscription_index"
           )

    create table(:change_subscriptions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "change_subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :change_id,
          references(:changes,
            column: :id,
            name: "change_subscriptions_change_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :channel_id,
          references(:channels,
            column: :id,
            name: "change_subscriptions_channel_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:change_subscriptions, [:user_id, :change_id, :channel_id],
             name: "change_subscriptions_unique_change_subscription_index",
             nulls_distinct: false
           )
  end

  def down do
    drop constraint(:change_subscriptions, "change_subscriptions_user_id_fkey")

    drop constraint(:change_subscriptions, "change_subscriptions_change_id_fkey")

    drop constraint(:change_subscriptions, "change_subscriptions_channel_id_fkey")

    drop_if_exists unique_index(:change_subscriptions, [:user_id, :change_id, :channel_id],
                     name: "change_subscriptions_unique_change_subscription_index"
                   )

    drop table(:change_subscriptions)

    drop constraint(:channel_subscriptions, "channel_subscriptions_user_id_fkey")

    drop constraint(:channel_subscriptions, "channel_subscriptions_channel_id_fkey")

    drop_if_exists unique_index(:channel_subscriptions, [:user_id, :channel_id],
                     name: "channel_subscriptions_unique_channel_subscription_index"
                   )

    drop table(:channel_subscriptions)

    drop constraint(:package_subscriptions, "package_subscriptions_user_id_fkey")

    drop constraint(:package_subscriptions, "package_subscriptions_package_id_fkey")

    drop constraint(:package_subscriptions, "package_subscriptions_channel_id_fkey")

    drop_if_exists unique_index(:package_subscriptions, [:user_id, :package_id, :channel_id],
                     name: "package_subscriptions_unique_package_subscription_index"
                   )

    drop table(:package_subscriptions)
  end
end
