defmodule Tracker.Repo.Migrations.RemoveMaintainerPersonalData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:maintainers) do
      remove :matrix
      remove :email
      remove :name
    end
  end

  def down do
    alter table(:maintainers) do
      add :name, :text
      add :email, :text
      add :matrix, :text
    end
  end
end
