defmodule Tracker.Repo.Migrations.RenameFeedTokenSeedToFeedToken do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :feed_token_seed, to: :feed_token

    create unique_index(:users, [:feed_token], name: "users_unique_feed_token_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:feed_token], name: "users_unique_feed_token_index")

    rename table(:users), :feed_token, to: :feed_token_seed
  end
end
