defmodule Tracker.Repo.Migrations.AddHeadRefToChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :head_ref, :text
    end
  end

  def down do
    alter table(:changes) do
      remove :head_ref
    end
  end
end
