defmodule Tracker.Repo.Migrations.AddChangeReconcileSkips do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:change_reconcile_skips, primary_key: false) do
      add :number, :bigint, null: false, primary_key: true
      add :kind, :text, null: false

      add :resolved_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:change_reconcile_skips, [:number],
             name: "change_reconcile_skips_unique_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:change_reconcile_skips, [:number],
                     name: "change_reconcile_skips_unique_number_index"
                   )

    drop table(:change_reconcile_skips)
  end
end
