defmodule Tracker.Repo.Migrations.AddFileIdIndexOptionRevisionFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:option_revision_files, [:file_id])
  end

  def down do
    drop_if_exists index(:option_revision_files, [:file_id])
  end
end
