defmodule Tracker.Repo.Migrations.MakeReleasedAtRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channel_revisions) do
      modify :released_at, :utc_datetime, null: false
    end
  end

  def down do
    alter table(:channel_revisions) do
      modify :released_at, :utc_datetime, null: true
    end
  end
end
