defmodule Tracker.Repo.Migrations.UserRolesAndOptionalGh do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :github_id, :bigint, null: true
      modify :github_username, :text, null: true
      add :role, :text, default: "user"
    end
  end

  def down do
    alter table(:users) do
      remove :role
      modify :github_username, :text, null: false
      modify :github_id, :bigint, null: false
    end
  end
end
