defmodule Tracker.Repo.Migrations.AddSavedNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notifications) do
      add :saved, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:notifications) do
      remove :saved
    end
  end
end
