defmodule Tracker.Repo.Migrations.AddFilesOverLimitToChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :files_over_limit, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:changes) do
      remove :files_over_limit
    end
  end
end
