defmodule Tracker.Repo.Migrations.WidenPackageSpanPayload do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:package_spans) do
      add :pname, :text
      add :outputs, {:array, :text}
      add :default_output, :text
      add :long_description, :text
      add :main_program, :text
      add :broken, :boolean
      add :unfree, :boolean
      add :insecure, :boolean
      add :unsupported, :boolean
      add :known_vulnerabilities, {:array, :text}
      add :platforms, {:array, :text}
      add :bad_platforms, {:array, :text}
      add :changelog, :text
      add :download_page, :text
      add :source_provenance, {:array, :text}
    end
  end

  def down do
    alter table(:package_spans) do
      remove :source_provenance
      remove :download_page
      remove :changelog
      remove :bad_platforms
      remove :platforms
      remove :known_vulnerabilities
      remove :unsupported
      remove :insecure
      remove :unfree
      remove :broken
      remove :main_program
      remove :long_description
      remove :default_output
      remove :outputs
      remove :pname
    end
  end
end
