defmodule Tracker.Repo.Migrations.FoldOptionPackagesIntoSpans do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:option_packages)

    create table(:option_package_spans, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :valid, :tstzrange, null: false
      add :fingerprint, :binary

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:channels,
            column: :id,
            name: "option_package_spans_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :option_id,
          references(:options,
            column: :id,
            name: "option_package_spans_option_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :package_id,
          references(:packages,
            column: :id,
            name: "option_package_spans_package_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    execute("""
    ALTER TABLE option_package_spans ADD CONSTRAINT option_package_spans_no_overlap EXCLUDE USING gist (channel_id WITH =, option_id WITH =, package_id WITH =, valid WITH &&)
    """)

    execute("""
    CREATE INDEX option_package_spans_current ON option_package_spans (channel_id, option_id, package_id) WHERE upper_inf(valid)
    """)
  end

  def down do
    execute("""
    DROP INDEX option_package_spans_current
    """)

    execute("""
    ALTER TABLE option_package_spans DROP CONSTRAINT option_package_spans_no_overlap
    """)

    drop constraint(:option_package_spans, "option_package_spans_channel_id_fkey")

    drop constraint(:option_package_spans, "option_package_spans_option_id_fkey")

    drop constraint(:option_package_spans, "option_package_spans_package_id_fkey")

    drop table(:option_package_spans)

    # Rollback would require recreating the table manually
  end
end
