defmodule Tracker.Repo.Migrations.AddLiveUi do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :live_ui, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:users) do
      remove :live_ui
    end
  end
end
