defmodule Tracker.Repo.Migrations.AddChangeAutoSubscribePreferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :auto_subscribe_authored_changes, :boolean, null: false, default: false
      add :auto_subscribe_merged_changes, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :auto_subscribe_merged_changes
      remove :auto_subscribe_authored_changes
    end
  end
end
