defmodule Tracker.Repo.Migrations.AddChangeChannels do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :merge_commit_sha, :text
    end

    create table(:change_channels, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :channel, :text, null: false
      add :landed_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_id,
          references(:changes,
            column: :id,
            name: "change_channels_change_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :channel_revision_id,
          references(:channel_revisions,
            column: :id,
            name: "change_channels_channel_revision_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:change_channels, [:change_id, :channel],
             name: "change_channels_unique_change_channel_index"
           )
  end

  def down do
    drop_if_exists unique_index(:change_channels, [:change_id, :channel],
                     name: "change_channels_unique_change_channel_index"
                   )

    drop constraint(:change_channels, "change_channels_change_id_fkey")

    drop constraint(:change_channels, "change_channels_channel_revision_id_fkey")

    drop table(:change_channels)

    alter table(:changes) do
      remove :merge_commit_sha
    end
  end
end
