defmodule Tracker.Repo.Migrations.AddChangeMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :author_github_id, :bigint
      add :merged_by_github_id, :bigint
      add :base_ref, :text
      add :labels, {:array, :text}
    end
  end

  def down do
    alter table(:changes) do
      remove :labels
      remove :base_ref
      remove :merged_by_github_id
      remove :author_github_id
    end
  end
end
