defmodule Tracker.Repo.Migrations.AddPackageFamilies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:package_families, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :ecosystem, :text, null: false, default: ""

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:package_families, [:name, :ecosystem],
             name: "package_families_unique_name_ecosystem_index"
           )

    alter table(:packages) do
      add :package_set, :text
      add :set_version, :text

      add :package_family_id,
          references(:package_families,
            column: :id,
            name: "packages_package_family_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create index(:packages, [:package_family_id])
  end

  def down do
    drop_if_exists index(:packages, [:package_family_id])

    drop constraint(:packages, "packages_package_family_id_fkey")

    alter table(:packages) do
      remove :package_family_id
      remove :set_version
      remove :package_set
    end

    drop_if_exists unique_index(:package_families, [:name, :ecosystem],
                     name: "package_families_unique_name_ecosystem_index"
                   )

    drop table(:package_families)
  end
end
