defmodule Tracker.Repo.Migrations.AddChangedFilesToChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :changed_files, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:changes) do
      remove :changed_files
    end
  end
end
