defmodule Tracker.Repo.Migrations.AddPackageVariantGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:packages) do
      add :package_variant_group_id, :bigint
    end

    create table(:package_variant_groups, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:packages) do
      modify :package_variant_group_id,
             references(:package_variant_groups,
               column: :id,
               name: "packages_package_variant_group_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:package_variant_groups) do
      add :position, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:package_variant_groups, [:position],
             name: "package_variant_groups_unique_position_index"
           )
  end

  def down do
    drop_if_exists unique_index(:package_variant_groups, [:position],
                     name: "package_variant_groups_unique_position_index"
                   )

    alter table(:package_variant_groups) do
      remove :updated_at
      remove :inserted_at
      remove :position
    end

    drop constraint(:packages, "packages_package_variant_group_id_fkey")

    alter table(:packages) do
      modify :package_variant_group_id, :bigint
    end

    drop table(:package_variant_groups)

    alter table(:packages) do
      remove :package_variant_group_id
    end
  end
end
