defmodule Tracker.Repo.Migrations.OptionSpanBoundaryIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX option_spans_opened_at ON option_spans (channel_id, lower(valid))
    """)

    execute("""
    CREATE INDEX option_spans_closed_at ON option_spans (channel_id, upper(valid))
    """)
  end

  def down do
    execute("""
    DROP INDEX option_spans_closed_at
    """)

    execute("""
    DROP INDEX option_spans_opened_at
    """)
  end
end
