defmodule Tracker.Repo.Migrations.DropChangeBranchDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:change_branches) do
      remove :updated_at
      remove :inserted_at
      remove :arrived_at
    end
  end

  def down do
    alter table(:change_branches) do
      add :arrived_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end
end
