defmodule Tracker.Repo.Migrations.SpanBoundaryIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX package_spans_opened_at ON package_spans (channel_id, lower(valid))
    """)

    execute("""
    CREATE INDEX package_spans_closed_at ON package_spans (channel_id, upper(valid))
    """)
  end

  def down do
    execute("""
    DROP INDEX package_spans_closed_at
    """)

    execute("""
    DROP INDEX package_spans_opened_at
    """)
  end
end
