defmodule Tracker.Repo.Migrations.AddPollingStatusToChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :polling_status, :text, null: false, default: "active"
    end
  end

  def down do
    alter table(:changes) do
      remove :polling_status
    end
  end
end
