defmodule Tracker.Repo.Migrations.SpanPayloadFingerprint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:option_file_spans) do
      add :fingerprint, :binary
    end

    alter table(:package_spans) do
      add :fingerprint, :binary
    end

    alter table(:option_spans) do
      add :fingerprint, :binary
    end
  end

  def down do
    alter table(:option_spans) do
      remove :fingerprint
    end

    alter table(:package_spans) do
      remove :fingerprint
    end

    alter table(:option_file_spans) do
      remove :fingerprint
    end
  end
end
