defmodule Tracker.Repo.Migrations.AddReleasesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:releases, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :base_url, :text, null: false
      add :released_at, :utc_datetime, null: false
      add :revision, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:channels,
            column: :id,
            name: "releases_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create index(:releases, [:channel_id, :released_at])

    create unique_index(:releases, [:channel_id, :base_url],
             name: "releases_unique_channel_base_url_index"
           )

    alter table(:channels) do
      add :pointer_etag, :text
      add :pointer_last_modified, :text
      add :pointer_revision, :text
    end
  end

  def down do
    alter table(:channels) do
      remove :pointer_revision
      remove :pointer_last_modified
      remove :pointer_etag
    end

    drop constraint(:releases, "releases_channel_id_fkey")

    drop_if_exists unique_index(:releases, [:channel_id, :base_url],
                     name: "releases_unique_channel_base_url_index"
                   )

    drop_if_exists index(:releases, [:channel_id, :released_at])

    drop table(:releases)
  end
end
