defmodule Tracker.Repo.Migrations.AddPackageCountToChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :package_count, :bigint, default: 0
    end
  end

  def down do
    alter table(:changes) do
      remove :package_count
    end
  end
end
