defmodule Tracker.Repo.Migrations.AddTypeToChangePackages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:change_packages) do
      add :type, :text, null: false, default: "changed"
    end
  end

  def down do
    alter table(:change_packages) do
      remove :type
    end
  end
end
