defmodule Tracker.Repo.Migrations.PipelineRetryBudget do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ingestion_pipelines) do
      add :retry_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:ingestion_pipelines) do
      remove :retry_count
    end
  end
end
