defmodule Tracker.Repo.Migrations.DropDeclarationsFromOptionRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:option_revisions) do
      remove :declarations
    end
  end

  def down do
    alter table(:option_revisions) do
      add :declarations, {:array, :text}
    end
  end
end
