defmodule Tracker.Repo.Migrations.AddNotificationsLedger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notifications, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :type, :text, null: false
      add :occurred_at, :utc_datetime, null: false
      add :read_at, :utc_datetime
      add :dedup_key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "notifications_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :package_id,
          references(:packages,
            column: :id,
            name: "notifications_package_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )

      add :channel_id,
          references(:channels,
            column: :id,
            name: "notifications_channel_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )

      add :channel_revision_id,
          references(:channel_revisions,
            column: :id,
            name: "notifications_channel_revision_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )

      add :change_id,
          references(:changes,
            column: :id,
            name: "notifications_change_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )

      add :change_branch_id,
          references(:change_branches,
            column: :id,
            name: "notifications_change_branch_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:notifications, [:dedup_key],
             name: "notifications_unique_dedup_key_index"
           )
  end

  def down do
    drop constraint(:notifications, "notifications_user_id_fkey")

    drop constraint(:notifications, "notifications_package_id_fkey")

    drop constraint(:notifications, "notifications_channel_id_fkey")

    drop constraint(:notifications, "notifications_channel_revision_id_fkey")

    drop constraint(:notifications, "notifications_change_id_fkey")

    drop constraint(:notifications, "notifications_change_branch_id_fkey")

    drop_if_exists unique_index(:notifications, [:dedup_key],
                     name: "notifications_unique_dedup_key_index"
                   )

    drop table(:notifications)
  end
end
