defmodule Tracker.Repo.Migrations.ChangeHomepageToArray do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def change do
    alter table(:packages) do
      remove :homepage, :text
      add :homepage, {:array, :text}
    end
  end
end
