defmodule Tracker.Repo.Migrations.AddReleasedAtToChannelRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channel_revisions) do
      add :released_at, :utc_datetime
    end
  end

  def down do
    alter table(:channel_revisions) do
      remove :released_at
    end
  end
end
