defmodule Tracker.Repo.Migrations.DropBranchResourceReshapeChangeBranches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channels) do
      remove :branch
    end

    create table(:change_branches, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :branch_name, :text, null: false
      add :arrived_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_id,
          references(:changes,
            column: :id,
            name: "change_branches_change_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :channel_revision_id,
          references(:channel_revisions,
            column: :id,
            name: "change_branches_channel_revision_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:change_branches, [:change_id, :branch_name],
             name: "change_branches_unique_change_branch_index"
           )
  end

  def down do
    drop_if_exists unique_index(:change_branches, [:change_id, :branch_name],
                     name: "change_branches_unique_change_branch_index"
                   )

    drop constraint(:change_branches, "change_branches_change_id_fkey")

    drop constraint(:change_branches, "change_branches_channel_revision_id_fkey")

    drop table(:change_branches)

    alter table(:channels) do
      add :branch, :text, null: false
    end
  end
end
