defmodule Tracker.Repo.Migrations.AddUserFeedTokenSeed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :feed_token_seed, :text
    end
  end

  def down do
    alter table(:users) do
      remove :feed_token_seed
    end
  end
end
