defmodule Tracker.Repo.Migrations.Trk105TeamCiString do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teams) do
      modify :short_name, :citext
    end
  end

  def down do
    alter table(:teams) do
      modify :short_name, :text
    end
  end
end
