defmodule Tracker.Repo.Migrations.ExtendChangeForPrLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :node_id, :text
      add :head_sha, :text
      add :gh_updated_at, :utc_datetime
      add :last_checked_at, :utc_datetime_usec
      add :closed_at, :utc_datetime
    end

    create unique_index(:changes, [:node_id], name: "changes_unique_node_id_index")
  end

  def down do
    drop_if_exists unique_index(:changes, [:node_id], name: "changes_unique_node_id_index")

    alter table(:changes) do
      remove :closed_at
      remove :last_checked_at
      remove :gh_updated_at
      remove :head_sha
      remove :node_id
    end
  end
end
