defmodule Tracker.Repo.Migrations.AddChangeFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      remove :changed_files
    end

    create table(:change_files, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_id,
          references(:changes,
            column: :id,
            name: "change_files_change_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :file_id,
          references(:files,
            column: :id,
            name: "change_files_file_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:change_files, [:change_id, :file_id],
             name: "change_files_unique_change_file_index"
           )
  end

  def down do
    drop_if_exists unique_index(:change_files, [:change_id, :file_id],
                     name: "change_files_unique_change_file_index"
                   )

    drop constraint(:change_files, "change_files_change_id_fkey")

    drop constraint(:change_files, "change_files_file_id_fkey")

    drop table(:change_files)

    alter table(:changes) do
      add :changed_files, {:array, :text}, null: false, default: []
    end
  end
end
