defmodule Tracker.Repo.Migrations.AddProcessingStatusToChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:changes) do
      add :processing_status, :text, default: "pending"
    end
  end

  def down do
    alter table(:changes) do
      remove :processing_status
    end
  end
end
