defmodule Tracker.Repo.Migrations.AddApiTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :jti, :text, null: false
      add :label, :text
      add :expires_at, :utc_datetime, null: false
      add :last_used_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subject_user_id,
          references(:users,
            column: :id,
            name: "api_tokens_subject_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :issued_by_user_id,
          references(:users,
            column: :id,
            name: "api_tokens_issued_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :revoked_by_user_id,
          references(:users,
            column: :id,
            name: "api_tokens_revoked_by_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:api_tokens, [:jti], name: "api_tokens_unique_jti_index")
  end

  def down do
    drop constraint(:api_tokens, "api_tokens_subject_user_id_fkey")

    drop constraint(:api_tokens, "api_tokens_issued_by_user_id_fkey")

    drop constraint(:api_tokens, "api_tokens_revoked_by_user_id_fkey")

    drop_if_exists unique_index(:api_tokens, [:jti], name: "api_tokens_unique_jti_index")

    drop table(:api_tokens)
  end
end
