defmodule Tracker.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:change_branches, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :arrived_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_id,
          references(:changes,
            column: :id,
            name: "change_branches_change_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :branch_id, :bigint, null: false
      add :channel_revision_id, :bigint
    end

    create table(:branches, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:change_branches) do
      modify :branch_id,
             references(:branches,
               column: :id,
               name: "change_branches_branch_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :channel_revision_id,
             references(:channel_revisions,
               column: :id,
               name: "change_branches_channel_revision_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create unique_index(:change_branches, [:change_id, :branch_id],
             name: "change_branches_unique_change_branch_index"
           )

    alter table(:branches) do
      add :name, :text, null: false
      add :kind, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :channel_id,
          references(:channels,
            column: :id,
            name: "branches_channel_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:branches, [:name], name: "branches_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:branches, [:name], name: "branches_unique_name_index")

    drop constraint(:branches, "branches_channel_id_fkey")

    alter table(:branches) do
      remove :channel_id
      remove :updated_at
      remove :inserted_at
      remove :kind
      remove :name
    end

    drop_if_exists unique_index(:change_branches, [:change_id, :branch_id],
                     name: "change_branches_unique_change_branch_index"
                   )

    drop constraint(:change_branches, "change_branches_branch_id_fkey")

    drop constraint(:change_branches, "change_branches_channel_revision_id_fkey")

    alter table(:change_branches) do
      modify :channel_revision_id, :bigint
      modify :branch_id, :bigint
    end

    drop table(:branches)

    drop constraint(:change_branches, "change_branches_change_id_fkey")

    drop table(:change_branches)
  end
end
