defmodule Tracker.Repo.Migrations.AddHydraPackageAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channel_revisions) do
      add :hydra_package_attributes, {:array, :text}
    end
  end

  def down do
    alter table(:channel_revisions) do
      remove :hydra_package_attributes
    end
  end
end
