defmodule Tracker.Repo.Migrations.AddUpdateLogPages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:update_log_pages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :attribute, :text, null: false
      add :url, :text, null: false
      add :namespace, :text
      add :package_name, :text
    end

    create unique_index(:update_log_pages, [:attribute],
             name: "update_log_pages_unique_attribute_index"
           )

    create index(:update_log_pages, [:namespace, :package_name])
  end

  def down do
    drop_if_exists index(:update_log_pages, [:namespace, :package_name])

    drop_if_exists unique_index(:update_log_pages, [:attribute],
                     name: "update_log_pages_unique_attribute_index"
                   )

    drop table(:update_log_pages)
  end
end
