defmodule Tracker.Repo.Migrations.AddChangesAndChangePackages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:changes, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :number, :bigint, null: false
      add :title, :text, null: false
      add :state, :text, null: false
      add :author, :text
      add :url, :text
      add :gh_created_at, :utc_datetime
      add :merged_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:changes, [:number], name: "changes_unique_number_index")

    create table(:change_packages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_id,
          references(:changes,
            column: :id,
            name: "change_packages_change_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :package_id,
          references(:packages,
            column: :id,
            name: "change_packages_package_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:change_packages, [:change_id, :package_id],
             name: "change_packages_unique_change_package_index"
           )
  end

  def down do
    drop_if_exists unique_index(:change_packages, [:change_id, :package_id],
                     name: "change_packages_unique_change_package_index"
                   )

    drop constraint(:change_packages, "change_packages_change_id_fkey")

    drop constraint(:change_packages, "change_packages_package_id_fkey")

    drop table(:change_packages)

    drop_if_exists unique_index(:changes, [:number], name: "changes_unique_number_index")

    drop table(:changes)
  end
end
