defmodule Tracker.Repo.Migrations.AddChannelResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:channels, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :display_name, :text, null: false
      add :branch, :text, null: false
      add :status, :text, null: false
      add :is_stable, :boolean, null: false, default: false
      add :options_source, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:channels, [:name], name: "channels_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:channels, [:name], name: "channels_unique_name_index")

    drop table(:channels)
  end
end
