defmodule Tracker.Repo.Migrations.AddReconstructionJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reconstruction_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :claimed_at, :utc_datetime_usec, null: false
      add :lease_expires_at, :utc_datetime_usec, null: false
      add :lease_token, :text, null: false
      add :status, :text, null: false, default: "claimed"
      add :last_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :change_id,
          references(:changes,
            column: :id,
            name: "reconstruction_jobs_change_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:reconstruction_jobs, [:change_id],
             name: "reconstruction_jobs_one_claimed_per_change_index",
             unique: true,
             where: "status = 'claimed'"
           )
  end

  def down do
    drop constraint(:reconstruction_jobs, "reconstruction_jobs_change_id_fkey")

    drop_if_exists index(:reconstruction_jobs, [:change_id],
                     name: "reconstruction_jobs_one_claimed_per_change_index"
                   )

    drop table(:reconstruction_jobs)
  end
end
